In [30]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [31]:
dataset = pd.read_csv("proper.csv", delimiter="\t")

In [32]:
dataset.drop("<VOL>", inplace=True, axis = 1)

In [33]:
from datetime import datetime
import calendar

In [34]:
dataset['<DATE>'] = dataset['<DATE>'].apply(lambda x: calendar.timegm(datetime.strptime(x, '%Y.%m.%d').utctimetuple()))

In [35]:
def EMA(data, col, n, arr):
    y = n-1
    for i in range(data['<CLOSE>'].size):
        if(i < y):
            arr.append(0)
        elif(i == y):
            av = data.iloc[:i, col].mean()
            arr.append(av)
        else:
            EM = ((data.iloc[i,col] * 2)/(n + 1)) + arr[i-1] * (1-(2/(n+1)))
            arr.append(EM)

In [36]:
EMA12 = []
EMA(dataset, 4, 12, EMA12)
EMA26 = []
EMA(dataset, 4, 26, EMA26)

In [37]:
dataset['<EMA12>'] = EMA12
dataset['<EMA26>'] = EMA26
dataset['<MACD>'] = dataset['<EMA12>'] - dataset['<EMA26>']

In [38]:
dataset = dataset.iloc[11:,:]

In [39]:
SIGNAL = []
EMA(dataset, 9, 9, SIGNAL)
dataset['<SIGNAL>'] = SIGNAL

In [40]:
dataset = dataset.iloc[9:,:]

In [41]:
def GL(data, gains, losses, col):
    for i in range(data['<CLOSE>'].size):
        if(i == 0):
            gains.append(0)
            losses.append(0)
        else:
            diff = data.iloc[i, col] - data.iloc[i-1, col]
            if(diff > 0):
                gains.append(diff)
                losses.append(0)
            elif(diff == 0):
                gains.append(0)
                losses.append(0)
            else:
                gains.append(0)
                losses.append(diff)

In [42]:
GAINS = []
LOSSES = []
GL(dataset, GAINS, LOSSES, 4)

In [43]:
dataset['<GAINS>'] = GAINS
dataset['<LOSSES>'] = LOSSES

In [44]:
dataset.head(20)

,<DATE>,<OPEN>,<HIGH>,<LOW>,<CLOSE>,<TICKVOL>,<SPREAD>,<EMA12>,<EMA26>,<MACD>,<SIGNAL>,<GAINS>,<LOSSES>
20,1579824000,0.68484,0.68574,0.68176,0.68260,26889,2,0.687020,0.000000,0.687020,0.689772,0.00000,0.00000
21,1579996800,0.68117,0.68182,0.68010,0.68013,3866,2,0.685960,0.000000,0.685960,0.689010,0.00000,-0.00247
22,1580083200,0.68012,0.68170,0.67527,0.67617,29263,2,0.684454,0.000000,0.684454,0.688099,0.00000,-0.00396
23,1580169600,0.67617,0.67666,0.67370,0.67638,29925,2,0.683212,0.000000,0.683212,0.687121,0.00021,0.00000
24,1580256000,0.67638,0.67772,0.67352,0.67532,30617,0,0.681997,0.000000,0.681997,0.686096,0.00000,-0.00106
25,1580342400,0.67532,0.67533,0.67000,0.67054,37511,2,0.680235,0.687530,-0.007295,0.547418,0.00000,-0.00478
26,1580428800,0.67054,0.67296,0.66828,0.66860,35169,2,0.678445,0.686127,-0.007683,0.436398,0.00000,-0.00194
27,1580601600,0.66852,0.66956,0.66841,0.66928,2209,2,0.677035,0.684879,-0.007845,0.347550,0.00068,0.00000
28,1580688000,0.66922,0.67070,0.66837,0.66897,34708,2,0.675794,0.683701,-0.007907,0.276458,0.00000,-0.00031
29,1580774400,0.66896,0.67418,0.66789,0.67311,34536,1,0.675381,0.682916,-0.007535,0.219660,0.00414,0.00000
30,1580860800,0.67311,0.67743,0.67237,0.67515,34091,2,0.675346,0.682341,-0.006996,0.174329,0.00204,0.00000
31,1580947200,0.67515,0.67649,0.67269,0.67313,27747,2,0.675005,0.681659,-0.006654,0.138132,0.00000,-0.00202
32,1581033600,0.67312,0.67314,0.66622,0.66766,29280,2,0.673875,0.680622,-0.006747,0.109156,0.00000,-0.00547
33,1581206400,0.66670,0.66784,0.66666,0.66699,2433,2,0.672816,0.679612,-0.006797,0.085966,0.00000,-0.00067
34,1581292800,0.66701,0.67074,0.66679,0.66895,30587,2,0.672221,0.678822,-0.006601,0.067452,0.00196,0.00000
35,1581379200,0.66895,0.67366,0.66810,0.67184,27546,2,0.672162,0.678305,-0.006143,0.052733,0.00289,0.00000
36,1581465600,0.67184,0.67499,0.67068,0.67130,29940,2,0.672030,0.677786,-0.005757,0.041035,0.00000,-0.00054
37,1581552000,0.67131,0.67449,0.67096,0.67189,31485,2,0.672008,0.677349,-0.005341,0.031760,0.00059,0.00000
38,1581638400,0.67191,0.67314,0.67092,0.67139,21164,2,0.671913,0.676908,-0.004995,0.024409,0.00000,-0.00050
39,1581811200,0.67208,0.67295,0.67167,0.67254,1271,2,0.672009,0.676584,-0.004575,0.018612,0.00115,0.00000

In [45]:
dataset = dataset.iloc[1:, :]

In [46]:
def RS(data, n, rs):
    y = n-1
    for i in range(data['<CLOSE>'].size):
        if(i < y):
            rs.append(0)
        else:
            GA = data.iloc[(i-y):i, 11].mean()
            LO = data.iloc[(i-y):i, 12].mean()
            div = GA/LO
            rs.append(div)

In [47]:
RelStr = []
RS(dataset, 14, RelStr)

In [48]:
dataset['<RS>'] = RelStr

In [49]:
dataset = dataset.iloc[14:, :]

In [50]:
dataset["<GROW>"] = dataset["<CLOSE>"] - dataset["<OPEN>"]

In [51]:
dataset.head()

,<DATE>,<OPEN>,<HIGH>,<LOW>,<CLOSE>,<TICKVOL>,<SPREAD>,<EMA12>,<EMA26>,<MACD>,<SIGNAL>,<GAINS>,<LOSSES>,<RS>,<GROW>
35,1581379200,0.66895,0.67366,0.66810,0.67184,27546,2,0.672162,0.678305,-0.006143,0.052733,0.00289,0.00000,-0.446809,0.00289
36,1581465600,0.67184,0.67499,0.67068,0.67130,29940,2,0.672030,0.677786,-0.005757,0.041035,0.00000,-0.00054,-0.733538,-0.00054
37,1581552000,0.67131,0.67449,0.67096,0.67189,31485,2,0.672008,0.677349,-0.005341,0.031760,0.00059,0.00000,-0.697439,0.00058
38,1581638400,0.67191,0.67314,0.67092,0.67139,21164,2,0.671913,0.676908,-0.004995,0.024409,0.00000,-0.00050,-0.781945,-0.00052
39,1581811200,0.67208,0.67295,0.67167,0.67254,1271,2,0.672009,0.676584,-0.004575,0.018612,0.00115,0.00000,-1.074236,0.00046

In [52]:
def CLGrowth(i):
        if(i == 0):
            return "one"
        elif(i < 0):
            return "zero"
        elif(i > 0):
            return "two"

In [53]:
dataset['<CLGROWTH>'] = dataset['<GROW>'].apply(CLGrowth)

In [54]:
dataset.head()

,<DATE>,<OPEN>,<HIGH>,<LOW>,<CLOSE>,<TICKVOL>,<SPREAD>,<EMA12>,<EMA26>,<MACD>,<SIGNAL>,<GAINS>,<LOSSES>,<RS>,<GROW>,<CLGROWTH>
35,1581379200,0.66895,0.67366,0.66810,0.67184,27546,2,0.672162,0.678305,-0.006143,0.052733,0.00289,0.00000,-0.446809,0.00289,two
36,1581465600,0.67184,0.67499,0.67068,0.67130,29940,2,0.672030,0.677786,-0.005757,0.041035,0.00000,-0.00054,-0.733538,-0.00054,zero
37,1581552000,0.67131,0.67449,0.67096,0.67189,31485,2,0.672008,0.677349,-0.005341,0.031760,0.00059,0.00000,-0.697439,0.00058,two
38,1581638400,0.67191,0.67314,0.67092,0.67139,21164,2,0.671913,0.676908,-0.004995,0.024409,0.00000,-0.00050,-0.781945,-0.00052,zero
39,1581811200,0.67208,0.67295,0.67167,0.67254,1271,2,0.672009,0.676584,-0.004575,0.018612,0.00115,0.00000,-1.074236,0.00046,two

In [55]:
dataset["<CLGROWTH>"] = dataset["<CLGROWTH>"].shift(-1)
dataset = dataset.iloc[:-1,:]

In [56]:
dataset.drop("<GROW>", inplace=True, axis = 1)

In [57]:
X = dataset.iloc[: ,:-1].values
y = dataset.iloc[:, -1].values

In [59]:
y

array(['zero', 'two', 'zero', ..., 'zero', 'zero', 'two'], dtype=object)

In [62]:
from sklearn.preprocessing import OneHotEncoder, LabelEncoder
from sklearn.compose import ColumnTransformer
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
y = np.array(ct.fit_transform(y.reshape(-1,1)))

In [63]:
y

array([[0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       ...,
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.]])

In [64]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X[:, 0:13])
X[:, 0:13] = imputer.transform(X[:, 0:13])

In [65]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state = 1)

In [66]:
from sklearn.preprocessing import StandardScaler

In [67]:
sc_Xtrain = StandardScaler()
X_train = sc_Xtrain.fit_transform(X_train)

sc_Xtest = StandardScaler()
X_test = sc_Xtest.fit_transform(X_test)

In [68]:
X_train

array([[ 5.08687414e-01,  1.16035653e+00,  1.13685913e+00, ...,
        -4.16650889e-01, -5.41509638e-01, -1.72414741e-01],
       [-7.54148890e-01, -1.73889294e-01, -1.78030989e-01, ...,
        -6.29729636e-02,  3.03112508e-01, -7.12205651e-02],
       [ 8.93492566e-01, -5.03130316e-01, -4.08448273e-01, ...,
         2.81638144e+00,  3.03112508e-01,  2.07525636e-03],
       ...,
       [-3.13355923e-01,  5.67244542e-01,  5.77770384e-01, ...,
         4.10499556e-02,  3.03112508e-01,  3.10170752e-01],
       [ 1.66843504e+00, -3.18905619e-01, -3.36681187e-01, ...,
        -4.16650889e-01, -3.47394724e-01, -1.14931120e-01],
       [-9.98095805e-01, -4.87419644e-01, -4.91926875e-01, ...,
        -4.16650889e-01, -2.00697193e-01,  1.51334059e-01]])

In [70]:
import tensorflow as tf

In [88]:
ann = tf.keras.models.Sequential()

In [89]:
ann.add(tf.keras.layers.Dense(units=12, activation='relu'))
ann.add(tf.keras.layers.Dense(units=12, activation='relu'))

In [90]:
ann.add(tf.keras.layers.Dense(units=3, activation='softmax'))

In [91]:
ann.compile(optimizer = 'adam', loss = 'categorical_crossentropy', metrics = ['accuracy'] )

In [92]:
ann.fit(X_train, y_train, batch_size=32, epochs= 200)

Epoch 1/200
165/165 [==============================] - 0s 2ms/step - loss: 0.8270 - accuracy: 0.5004
Epoch 2/200
165/165 [==============================] - 0s 2ms/step - loss: 0.7362 - accuracy: 0.5112
Epoch 3/200
165/165 [==============================] - 0s 2ms/step - loss: 0.7269 - accuracy: 0.5203
Epoch 4/200
165/165 [==============================] - 0s 2ms/step - loss: 0.7234 - accuracy: 0.5342
Epoch 5/200
165/165 [==============================] - 0s 2ms/step - loss: 0.7225 - accuracy: 0.5277
Epoch 6/200
165/165 [==============================] - 0s 2ms/step - loss: 0.7213 - accuracy: 0.5302
Epoch 7/200
165/165 [==============================] - 0s 2ms/step - loss: 0.7210 - accuracy: 0.5323
Epoch 8/200
165/165 [==============================] - 0s 2ms/step - loss: 0.7203 - accuracy: 0.5271
Epoch 9/200
165/165 [==============================] - 0s 2ms/step - loss: 0.7196 - accuracy: 0.5311
Epoch 10/200
165/165 [==============================] - 0s 2ms/step - loss: 0.7195 - accuracy: 0.5298
Epoch 11/200
165/165 [==============================] - 0s 2ms/step - loss: 0.7184 - accuracy: 0.5292
Epoch 12/200
165/165 [==============================] - 0s 2ms/step - loss: 0.7187 - accuracy: 0.5311
Epoch 13/200
165/165 [==============================] - 0s 2ms/step - loss: 0.7186 - accuracy: 0.5285
Epoch 14/200
165/165 [==============================] - 0s 2ms/step - loss: 0.7186 - accuracy: 0.5268
Epoch 15/200
165/165 [==============================] - 0s 2ms/step - loss: 0.7176 - accuracy: 0.5281
Epoch 16/200
165/165 [==============================] - 0s 2ms/step - loss: 0.7181 - accuracy: 0.5283
Epoch 17/200
165/165 [==============================] - 0s 2ms/step - loss: 0.7173 - accuracy: 0.5408
Epoch 18/200
165/165 [==============================] - 0s 2ms/step - loss: 0.7169 - accuracy: 0.5383
Epoch 19/200
165/165 [==============================] - 0s 2ms/step - loss: 0.7163 - accuracy: 0.5383
Epoch 20/200
165/165 [==============================] - 0s 3ms/step - loss: 0.7166 - accuracy: 0.5309
Epoch 21/200
165/165 [==============================] - 0s 2ms/step - loss: 0.7164 - accuracy: 0.5395
Epoch 22/200
165/165 [==============================] - 0s 2ms/step - loss: 0.7165 - accuracy: 0.5372
Epoch 23/200
165/165 [==============================] - 0s 2ms/step - loss: 0.7159 - accuracy: 0.5387
Epoch 24/200
165/165 [==============================] - 0s 2ms/step - loss: 0.7157 - accuracy: 0.5387
Epoch 25/200
165/165 [==============================] - 0s 2ms/step - loss: 0.7164 - accuracy: 0.5309
Epoch 26/200
165/165 [==============================] - 0s 2ms/step - loss: 0.7154 - accuracy: 0.5408
Epoch 27/200
165/165 [==============================] - 0s 2ms/step - loss: 0.7151 - accuracy: 0.5423
Epoch 28/200
165/165 [==============================] - 0s 2ms/step - loss: 0.7154 - accuracy: 0.5374
Epoch 29/200
165/165 [==============================] - 0s 2ms/step - loss: 0.7148 - accuracy: 0.5374
Epoch 30/200
165/165 [==============================] - 0s 2ms/step - loss: 0.7150 - accuracy: 0.5383
Epoch 31/200
165/165 [==============================] - 0s 2ms/step - loss: 0.7145 - accuracy: 0.5364
Epoch 32/200
165/165 [==============================] - 0s 2ms/step - loss: 0.7148 - accuracy: 0.5387
Epoch 33/200
165/165 [==============================] - 0s 2ms/step - loss: 0.7149 - accuracy: 0.5359
Epoch 34/200
165/165 [==============================] - 0s 2ms/step - loss: 0.7147 - accuracy: 0.5420
Epoch 35/200
165/165 [==============================] - 0s 2ms/step - loss: 0.7144 - accuracy: 0.5363
Epoch 36/200
165/165 [==============================] - 0s 3ms/step - loss: 0.7135 - accuracy: 0.5476
Epoch 37/200
165/165 [==============================] - 0s 2ms/step - loss: 0.7145 - accuracy: 0.5380
Epoch 38/200
165/165 [==============================] - 0s 2ms/step - loss: 0.7139 - accuracy: 0.5406
Epoch 39/200
165/165 [==============================] - 0s 2ms/step - loss: 0.7139 - accuracy: 0.5446
Epoch 40/200
165/165 [==============================] - 0s 2ms/step - loss: 0.7133 - accuracy: 0.5383
Epoch 41/200
165/165 [==============================] - 0s 2ms/step - loss: 0.7131 - accuracy: 0.5429
Epoch 42/200
165/165 [==============================] - 0s 3ms/step - loss: 0.7132 - accuracy: 0.5397
Epoch 43/200
165/165 [==============================] - 0s 2ms/step - loss: 0.7130 - accuracy: 0.5469
Epoch 44/200
165/165 [==============================] - 0s 2ms/step - loss: 0.7125 - accuracy: 0.5442
Epoch 45/200
165/165 [==============================] - 0s 2ms/step - loss: 0.7139 - accuracy: 0.5364
Epoch 46/200
165/165 [==============================] - 0s 2ms/step - loss: 0.7128 - accuracy: 0.5437
Epoch 47/200
165/165 [==============================] - 0s 2ms/step - loss: 0.7126 - accuracy: 0.5399
Epoch 48/200
165/165 [==============================] - 0s 2ms/step - loss: 0.7123 - accuracy: 0.5427
Epoch 49/200
165/165 [==============================] - 0s 2ms/step - loss: 0.7125 - accuracy: 0.5416
Epoch 50/200
165/165 [==============================] - 0s 2ms/step - loss: 0.7123 - accuracy: 0.5380
Epoch 51/200
165/165 [==============================] - 0s 2ms/step - loss: 0.7117 - accuracy: 0.5421
Epoch 52/200
165/165 [==============================] - 0s 2ms/step - loss: 0.7123 - accuracy: 0.5456
Epoch 53/200
165/165 [==============================] - 0s 2ms/step - loss: 0.7119 - accuracy: 0.5499
Epoch 54/200
165/165 [==============================] - 0s 2ms/step - loss: 0.7112 - accuracy: 0.5454
Epoch 55/200
165/165 [==============================] - 1s 3ms/step - loss: 0.7117 - accuracy: 0.5444
Epoch 56/200
165/165 [==============================] - 0s 2ms/step - loss: 0.7121 - accuracy: 0.5397
Epoch 57/200
165/165 [==============================] - 0s 2ms/step - loss: 0.7108 - accuracy: 0.5490
Epoch 58/200
165/165 [==============================] - 0s 2ms/step - loss: 0.7118 - accuracy: 0.5478
Epoch 59/200
165/165 [==============================] - 0s 2ms/step - loss: 0.7108 - accuracy: 0.5507
Epoch 60/200
165/165 [==============================] - 0s 2ms/step - loss: 0.7106 - accuracy: 0.5478
Epoch 61/200
165/165 [==============================] - 0s 2ms/step - loss: 0.7103 - accuracy: 0.5516
Epoch 62/200
165/165 [==============================] - 0s 2ms/step - loss: 0.7108 - accuracy: 0.5450
Epoch 63/200
165/165 [==============================] - 0s 3ms/step - loss: 0.7111 - accuracy: 0.5448
Epoch 64/200
165/165 [==============================] - 0s 2ms/step - loss: 0.7100 - accuracy: 0.5467
Epoch 65/200
165/165 [==============================] - 0s 2ms/step - loss: 0.7102 - accuracy: 0.5457
Epoch 66/200
165/165 [==============================] - 0s 3ms/step - loss: 0.7103 - accuracy: 0.5486
Epoch 67/200
165/165 [==============================] - 0s 2ms/step - loss: 0.7096 - accuracy: 0.5461
Epoch 68/200
165/165 [==============================] - 0s 2ms/step - loss: 0.7096 - accuracy: 0.5442
Epoch 69/200
165/165 [==============================] - 0s 2ms/step - loss: 0.7091 - accuracy: 0.5492
Epoch 70/200
165/165 [==============================] - 0s 2ms/step - loss: 0.7099 - accuracy: 0.5448
Epoch 71/200
165/165 [==============================] - 0s 2ms/step - loss: 0.7100 - accuracy: 0.5433
Epoch 72/200
165/165 [==============================] - 0s 2ms/step - loss: 0.7093 - accuracy: 0.5465
Epoch 73/200
165/165 [==============================] - 0s 2ms/step - loss: 0.7091 - accuracy: 0.5533
Epoch 74/200
165/165 [==============================] - 0s 3ms/step - loss: 0.7098 - accuracy: 0.5448
Epoch 75/200
165/165 [==============================] - 0s 2ms/step - loss: 0.7093 - accuracy: 0.5516
Epoch 76/200
165/165 [==============================] - 0s 2ms/step - loss: 0.7085 - accuracy: 0.5543
Epoch 77/200
165/165 [==============================] - 0s 2ms/step - loss: 0.7089 - accuracy: 0.5499
Epoch 78/200
165/165 [==============================] - 0s 2ms/step - loss: 0.7085 - accuracy: 0.5490
Epoch 79/200
165/165 [==============================] - 0s 2ms/step - loss: 0.7086 - accuracy: 0.5505
Epoch 80/200
165/165 [==============================] - 0s 2ms/step - loss: 0.7082 - accuracy: 0.5552
Epoch 81/200
165/165 [==============================] - 0s 2ms/step - loss: 0.7080 - accuracy: 0.5558
Epoch 82/200
165/165 [==============================] - 0s 2ms/step - loss: 0.7083 - accuracy: 0.5537
Epoch 83/200
165/165 [==============================] - 0s 2ms/step - loss: 0.7077 - accuracy: 0.5499
Epoch 84/200
165/165 [==============================] - 0s 2ms/step - loss: 0.7083 - accuracy: 0.5511
Epoch 85/200
165/165 [==============================] - 0s 2ms/step - loss: 0.7087 - accuracy: 0.5541
Epoch 86/200
165/165 [==============================] - 0s 2ms/step - loss: 0.7079 - accuracy: 0.5501
Epoch 87/200
165/165 [==============================] - 0s 2ms/step - loss: 0.7077 - accuracy: 0.5554
Epoch 88/200
165/165 [==============================] - 0s 2ms/step - loss: 0.7070 - accuracy: 0.5514
Epoch 89/200
165/165 [==============================] - 0s 2ms/step - loss: 0.7077 - accuracy: 0.5560
Epoch 90/200
165/165 [==============================] - 0s 2ms/step - loss: 0.7075 - accuracy: 0.5513
Epoch 91/200
165/165 [==============================] - 0s 2ms/step - loss: 0.7077 - accuracy: 0.5516
Epoch 92/200
165/165 [==============================] - 0s 2ms/step - loss: 0.7065 - accuracy: 0.5549
Epoch 93/200
165/165 [==============================] - 0s 2ms/step - loss: 0.7074 - accuracy: 0.5533
Epoch 94/200
165/165 [==============================] - 0s 2ms/step - loss: 0.7074 - accuracy: 0.5575
Epoch 95/200
165/165 [==============================] - 0s 2ms/step - loss: 0.7072 - accuracy: 0.5492
Epoch 96/200
165/165 [==============================] - 0s 2ms/step - loss: 0.7073 - accuracy: 0.5495
Epoch 97/200
165/165 [==============================] - 0s 2ms/step - loss: 0.7062 - accuracy: 0.5516
Epoch 98/200
165/165 [==============================] - 0s 2ms/step - loss: 0.7068 - accuracy: 0.5573
Epoch 99/200
165/165 [==============================] - 0s 2ms/step - loss: 0.7069 - accuracy: 0.5554
Epoch 100/200
165/165 [==============================] - 0s 2ms/step - loss: 0.7060 - accuracy: 0.5499
Epoch 101/200
165/165 [==============================] - 0s 2ms/step - loss: 0.7060 - accuracy: 0.5571
Epoch 102/200
165/165 [==============================] - 0s 2ms/step - loss: 0.7071 - accuracy: 0.5530
Epoch 103/200
165/165 [==============================] - 0s 2ms/step - loss: 0.7062 - accuracy: 0.5626
Epoch 104/200
165/165 [==============================] - 0s 2ms/step - loss: 0.7062 - accuracy: 0.5513
Epoch 105/200
165/165 [==============================] - 0s 3ms/step - loss: 0.7072 - accuracy: 0.5440
Epoch 106/200
165/165 [==============================] - 0s 2ms/step - loss: 0.7063 - accuracy: 0.5528
Epoch 107/200
165/165 [==============================] - 0s 2ms/step - loss: 0.7061 - accuracy: 0.5543
Epoch 108/200
165/165 [==============================] - 0s 2ms/step - loss: 0.7061 - accuracy: 0.5602
Epoch 109/200
165/165 [==============================] - 0s 2ms/step - loss: 0.7056 - accuracy: 0.5594
Epoch 110/200
165/165 [==============================] - 0s 2ms/step - loss: 0.7060 - accuracy: 0.5516
Epoch 111/200
165/165 [==============================] - 0s 2ms/step - loss: 0.7056 - accuracy: 0.5549
Epoch 112/200
165/165 [==============================] - 0s 2ms/step - loss: 0.7049 - accuracy: 0.5573
Epoch 113/200
165/165 [==============================] - 0s 2ms/step - loss: 0.7060 - accuracy: 0.5522
Epoch 114/200
165/165 [==============================] - 0s 2ms/step - loss: 0.7053 - accuracy: 0.5541
Epoch 115/200
165/165 [==============================] - 0s 2ms/step - loss: 0.7063 - accuracy: 0.5541
Epoch 116/200
165/165 [==============================] - 0s 2ms/step - loss: 0.7051 - accuracy: 0.5609
Epoch 117/200
165/165 [==============================] - 0s 2ms/step - loss: 0.7053 - accuracy: 0.5564
Epoch 118/200
165/165 [==============================] - 0s 2ms/step - loss: 0.7050 - accuracy: 0.5545
Epoch 119/200
165/165 [==============================] - 0s 2ms/step - loss: 0.7052 - accuracy: 0.5566
Epoch 120/200
165/165 [==============================] - 0s 2ms/step - loss: 0.7048 - accuracy: 0.5594
Epoch 121/200
165/165 [==============================] - 0s 2ms/step - loss: 0.7043 - accuracy: 0.5564
Epoch 122/200
165/165 [==============================] - 0s 2ms/step - loss: 0.7056 - accuracy: 0.5554
Epoch 123/200
165/165 [==============================] - 0s 2ms/step - loss: 0.7044 - accuracy: 0.5588
Epoch 124/200
165/165 [==============================] - 0s 2ms/step - loss: 0.7049 - accuracy: 0.5634
Epoch 125/200
165/165 [==============================] - 0s 2ms/step - loss: 0.7049 - accuracy: 0.5581
Epoch 126/200
165/165 [==============================] - 0s 2ms/step - loss: 0.7043 - accuracy: 0.5602
Epoch 127/200
165/165 [==============================] - 0s 2ms/step - loss: 0.7038 - accuracy: 0.5640
Epoch 128/200
165/165 [==============================] - 0s 2ms/step - loss: 0.7046 - accuracy: 0.5497
Epoch 129/200
165/165 [==============================] - 0s 2ms/step - loss: 0.7042 - accuracy: 0.5583
Epoch 130/200
165/165 [==============================] - 0s 2ms/step - loss: 0.7040 - accuracy: 0.5532
Epoch 131/200
165/165 [==============================] - 0s 2ms/step - loss: 0.7046 - accuracy: 0.5558
Epoch 132/200
165/165 [==============================] - 0s 2ms/step - loss: 0.7037 - accuracy: 0.5564
Epoch 133/200
165/165 [==============================] - 0s 2ms/step - loss: 0.7044 - accuracy: 0.5592
Epoch 134/200
165/165 [==============================] - 0s 2ms/step - loss: 0.7039 - accuracy: 0.5556
Epoch 135/200
165/165 [==============================] - 0s 2ms/step - loss: 0.7034 - accuracy: 0.5674
Epoch 136/200
165/165 [==============================] - 0s 2ms/step - loss: 0.7045 - accuracy: 0.5571
Epoch 137/200
165/165 [==============================] - 0s 2ms/step - loss: 0.7038 - accuracy: 0.5642
Epoch 138/200
165/165 [==============================] - 0s 2ms/step - loss: 0.7040 - accuracy: 0.5581
Epoch 139/200
165/165 [==============================] - 0s 2ms/step - loss: 0.7037 - accuracy: 0.5494
Epoch 140/200
165/165 [==============================] - 0s 2ms/step - loss: 0.7038 - accuracy: 0.5606
Epoch 141/200
165/165 [==============================] - 0s 2ms/step - loss: 0.7034 - accuracy: 0.5626
Epoch 142/200
165/165 [==============================] - 0s 2ms/step - loss: 0.7036 - accuracy: 0.5647
Epoch 143/200
165/165 [==============================] - 0s 2ms/step - loss: 0.7040 - accuracy: 0.5615
Epoch 144/200
165/165 [==============================] - 0s 2ms/step - loss: 0.7033 - accuracy: 0.5569
Epoch 145/200
165/165 [==============================] - 0s 2ms/step - loss: 0.7034 - accuracy: 0.5569
Epoch 146/200
165/165 [==============================] - 0s 2ms/step - loss: 0.7038 - accuracy: 0.5619
Epoch 147/200
165/165 [==============================] - 0s 2ms/step - loss: 0.7036 - accuracy: 0.5666
Epoch 148/200
165/165 [==============================] - 0s 2ms/step - loss: 0.7039 - accuracy: 0.5583
Epoch 149/200
165/165 [==============================] - 0s 2ms/step - loss: 0.7047 - accuracy: 0.5611
Epoch 150/200
165/165 [==============================] - 0s 2ms/step - loss: 0.7036 - accuracy: 0.5588
Epoch 151/200
165/165 [==============================] - 0s 2ms/step - loss: 0.7031 - accuracy: 0.5573
Epoch 152/200
165/165 [==============================] - 0s 2ms/step - loss: 0.7026 - accuracy: 0.5619
Epoch 153/200
165/165 [==============================] - 0s 2ms/step - loss: 0.7027 - accuracy: 0.5683
Epoch 154/200
165/165 [==============================] - 0s 2ms/step - loss: 0.7028 - accuracy: 0.5619
Epoch 155/200
165/165 [==============================] - 0s 2ms/step - loss: 0.7026 - accuracy: 0.5598
Epoch 156/200
165/165 [==============================] - 0s 2ms/step - loss: 0.7031 - accuracy: 0.5545
Epoch 157/200
165/165 [==============================] - 0s 2ms/step - loss: 0.7023 - accuracy: 0.5655
Epoch 158/200
165/165 [==============================] - 0s 2ms/step - loss: 0.7035 - accuracy: 0.5594
Epoch 159/200
165/165 [==============================] - 0s 2ms/step - loss: 0.7038 - accuracy: 0.5545
Epoch 160/200
165/165 [==============================] - 0s 2ms/step - loss: 0.7020 - accuracy: 0.5604
Epoch 161/200
165/165 [==============================] - 0s 2ms/step - loss: 0.7033 - accuracy: 0.5606
Epoch 162/200
165/165 [==============================] - 0s 2ms/step - loss: 0.7022 - accuracy: 0.5640
Epoch 163/200
165/165 [==============================] - 0s 2ms/step - loss: 0.7028 - accuracy: 0.5543
Epoch 164/200
165/165 [==============================] - 0s 2ms/step - loss: 0.7020 - accuracy: 0.5579
Epoch 165/200
165/165 [==============================] - 0s 2ms/step - loss: 0.7029 - accuracy: 0.5583
Epoch 166/200
165/165 [==============================] - 0s 2ms/step - loss: 0.7028 - accuracy: 0.5587
Epoch 167/200
165/165 [==============================] - 0s 2ms/step - loss: 0.7029 - accuracy: 0.5600
Epoch 168/200
165/165 [==============================] - 0s 2ms/step - loss: 0.7017 - accuracy: 0.5600
Epoch 169/200
165/165 [==============================] - 0s 2ms/step - loss: 0.7017 - accuracy: 0.5676
Epoch 170/200
165/165 [==============================] - 0s 2ms/step - loss: 0.7022 - accuracy: 0.5607
Epoch 171/200
165/165 [==============================] - 0s 2ms/step - loss: 0.7030 - accuracy: 0.5592
Epoch 172/200
165/165 [==============================] - 0s 2ms/step - loss: 0.7029 - accuracy: 0.5619
Epoch 173/200
165/165 [==============================] - 0s 2ms/step - loss: 0.7022 - accuracy: 0.5628
Epoch 174/200
165/165 [==============================] - 0s 2ms/step - loss: 0.7024 - accuracy: 0.5642
Epoch 175/200
165/165 [==============================] - 0s 2ms/step - loss: 0.7026 - accuracy: 0.5615
Epoch 176/200
165/165 [==============================] - 0s 2ms/step - loss: 0.7022 - accuracy: 0.5693
Epoch 177/200
165/165 [==============================] - 0s 2ms/step - loss: 0.7022 - accuracy: 0.5651
Epoch 178/200
165/165 [==============================] - 0s 2ms/step - loss: 0.7017 - accuracy: 0.5636
Epoch 179/200
165/165 [==============================] - 0s 2ms/step - loss: 0.7023 - accuracy: 0.5615
Epoch 180/200
165/165 [==============================] - 0s 2ms/step - loss: 0.7020 - accuracy: 0.5583
Epoch 181/200
165/165 [==============================] - 0s 2ms/step - loss: 0.7016 - accuracy: 0.5598
Epoch 182/200
165/165 [==============================] - 0s 2ms/step - loss: 0.7024 - accuracy: 0.5699
Epoch 183/200
165/165 [==============================] - 0s 2ms/step - loss: 0.7007 - accuracy: 0.5683
Epoch 184/200
165/165 [==============================] - 0s 2ms/step - loss: 0.7019 - accuracy: 0.5699
Epoch 185/200
165/165 [==============================] - 0s 2ms/step - loss: 0.7014 - accuracy: 0.5689
Epoch 186/200
165/165 [==============================] - 0s 2ms/step - loss: 0.7021 - accuracy: 0.5587
Epoch 187/200
165/165 [==============================] - 0s 2ms/step - loss: 0.7017 - accuracy: 0.5636
Epoch 188/200
165/165 [==============================] - 0s 2ms/step - loss: 0.7019 - accuracy: 0.5626
Epoch 189/200
165/165 [==============================] - 0s 2ms/step - loss: 0.7006 - accuracy: 0.5649
Epoch 190/200
165/165 [==============================] - 0s 2ms/step - loss: 0.7010 - accuracy: 0.5579
Epoch 191/200
165/165 [==============================] - 0s 2ms/step - loss: 0.7011 - accuracy: 0.5674
Epoch 192/200
165/165 [==============================] - 0s 2ms/step - loss: 0.7021 - accuracy: 0.5607
Epoch 193/200
165/165 [==============================] - 0s 2ms/step - loss: 0.7014 - accuracy: 0.5602
Epoch 194/200
165/165 [==============================] - 0s 2ms/step - loss: 0.7014 - accuracy: 0.5634
Epoch 195/200
165/165 [==============================] - 0s 2ms/step - loss: 0.7015 - accuracy: 0.5604
Epoch 196/200

In [95]:
y_pred = ann.predict(X_test)

In [99]:
from sklearn.metrics import confusion_matrix, accuracy_score

In [100]:
yp = y_pred.argmax(1)

In [101]:
yt = y_test.argmax(1)

In [109]:
cmT = confusion_matrix(yt, yp)
accT = accuracy_score(yt, yp)

In [110]:
cmT

array([[  0,  14,   1],
       [  0, 502, 165],
       [  0, 480, 155]])

In [111]:
accT

0.4988610478359909

<h1>Testing on new data</h1>

In [93]:
datasetTest = pd.read_csv("AUDUSD_JUNE18.csv", delimiter="\t")
datasetTest.drop("<VOL>", inplace=True, axis = 1)
datasetTest.head()

       <DATE>   <OPEN>   <HIGH>    <LOW>  <CLOSE>  <TICKVOL>  <SPREAD>
0  2021.01.03  0.76967  0.77140  0.76898  0.77110       2208         2
1  2021.01.04  0.77110  0.77405  0.76424  0.76693      63202         2
2  2021.01.05  0.76693  0.77775  0.76608  0.77624      63957         2
3  2021.01.06  0.77628  0.78201  0.77329  0.78155      89942         2
4  2021.01.07  0.78156  0.78162  0.77255  0.77685      65755         2

In [112]:
datasetTest.tail()

         <DATE>   <OPEN>   <HIGH>    <LOW>  <CLOSE>  <TICKVOL>  <SPREAD>
139  2021.06.14  0.77075  0.77258  0.76936  0.77116      27581         1
140  2021.06.15  0.77115  0.77165  0.76741  0.76855      31281         1
141  2021.06.16  0.76857  0.77155  0.76048  0.76146      48136         2
142  2021.06.17  0.76145  0.76454  0.75396  0.75566      56945         2
143  2021.06.18  0.75566  0.75608  0.74787  0.74789      57720         2

In [113]:
datasetTest['<DATE>'] = datasetTest['<DATE>'].apply(lambda x: calendar.timegm(datetime.strptime(x, '%Y.%m.%d').utctimetuple()))

In [114]:
tEMA12 = []
EMA(datasetTest, 4, 12, tEMA12)

In [115]:
datasetTest['<EMA12>'] = tEMA12

In [116]:
datasetTest.head(20)

,<DATE>,<OPEN>,<HIGH>,<LOW>,<CLOSE>,<TICKVOL>,<SPREAD>,<EMA12>
0,1609632000,0.76967,0.77140,0.76898,0.77110,2208,2,0.000000
1,1609718400,0.77110,0.77405,0.76424,0.76693,63202,2,0.000000
2,1609804800,0.76693,0.77775,0.76608,0.77624,63957,2,0.000000
3,1609891200,0.77628,0.78201,0.77329,0.78155,89942,2,0.000000
4,1609977600,0.78156,0.78162,0.77255,0.77685,65755,2,0.000000
5,1610064000,0.77684,0.77987,0.77283,0.77648,77841,2,0.000000
6,1610236800,0.77540,0.77598,0.77117,0.77204,2938,2,0.000000
7,1610323200,0.77204,0.77309,0.76663,0.77071,64368,2,0.000000
8,1610409600,0.77071,0.77774,0.76867,0.77755,59699,2,0.000000
9,1610496000,0.77755,0.77814,0.77217,0.77463,54884,2,0.000000
10,1610582400,0.77463,0.78054,0.77286,0.77755,55408,2,0.000000
11,1610668800,0.77754,0.77886,0.76816,0.77032,56918,2,0.774694
12,1610841600,0.77064,0.77103,0.76830,0.76830,2060,2,0.773710
13,1610928000,0.76831,0.77041,0.76588,0.76847,47028,2,0.772904
14,1611014400,0.76847,0.77251,0.76846,0.77133,50564,1,0.772662
15,1611100800,0.77133,0.77632,0.77004,0.77548,49953,2,0.773095
16,1611187200,0.77548,0.77820,0.77413,0.77595,52107,1,0.773534
17,1611273600,0.77595,0.77688,0.77019,0.77153,49973,2,0.773226
18,1611446400,0.77126,0.77209,0.77054,0.77133,1909,2,0.772934
19,1611532800,0.77138,0.77473,0.76828,0.77147,58122,2,0.772709

In [117]:
datasetTest = datasetTest.iloc[11:,:]

In [118]:
tEMA26 = []
EMA(datasetTest, 4, 26, tEMA26)

In [119]:
datasetTest['<EMA26>'] = tEMA26

<ipython-input-119-418cfa99d0de>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  datasetTest['<EMA26>'] = tEMA26

In [120]:
datasetTest = datasetTest.iloc[25:,:]

In [121]:
datasetTest['<MACD>'] = datasetTest['<EMA12>'] - datasetTest['<EMA26>']

In [122]:
tSIGNAL = []
EMA(datasetTest, 9, 9, tSIGNAL)
datasetTest['<SIGNAL>'] = tSIGNAL

In [123]:
datasetTest = datasetTest.iloc[8:,:]

In [124]:
tGAINS = []
tLOSSES = []
GL(datasetTest, tGAINS, tLOSSES, 4)

In [125]:
datasetTest['<GAINS>'] = tGAINS
datasetTest['<LOSSES>'] = tLOSSES

In [126]:
tRelStr = []
RS(datasetTest, 14, tRelStr)

In [127]:
datasetTest['<RS>'] = tRelStr

In [128]:
datasetTest["<GROW>"] = datasetTest["<CLOSE>"] - datasetTest["<OPEN>"]

In [129]:
datasetTest['<CLGROWTH>'] = datasetTest['<GROW>'].apply(CLGrowth)

In [130]:
datasetTest["<CLGROWTH>"] = datasetTest["<CLGROWTH>"].shift(-1)
datasetTest = datasetTest.iloc[:-1,:]

In [131]:
datasetTest.drop("<GROW>", inplace=True, axis = 1)

In [133]:
datasetTest.head()

,<DATE>,<OPEN>,<HIGH>,<LOW>,<CLOSE>,<TICKVOL>,<SPREAD>,<EMA12>,<EMA26>,<MACD>,<SIGNAL>,<GAINS>,<LOSSES>,<RS>,<CLGROWTH>
44,1614038400,0.79141,0.79345,0.78803,0.79069,61275,2,0.781464,0.775894,0.005570,0.003234,0.00000,0.00000,0.0,two
45,1614124800,0.79069,0.79777,0.78951,0.79756,66777,1,0.783940,0.777498,0.006442,0.003875,0.00687,0.00000,0.0,zero
46,1614211200,0.79755,0.80071,0.78585,0.78623,84984,2,0.784292,0.778145,0.006147,0.004330,0.00000,-0.01133,0.0,zero
47,1614297600,0.78623,0.78717,0.76920,0.77030,91560,2,0.782140,0.777564,0.004576,0.004379,0.00000,-0.01593,0.0,two
48,1614470400,0.77102,0.77590,0.77073,0.77524,2837,2,0.781078,0.777392,0.003686,0.004240,0.00494,0.00000,0.0,two

In [132]:
Xt = datasetTest.iloc[: ,:-1].values
yt = datasetTest.iloc[:, -1].values

In [134]:
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
yt = np.array(ct.fit_transform(yt.reshape(-1,1)))

In [135]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(Xt[:, 0:13])
Xt[:, 0:13] = imputer.transform(Xt[:, 0:13])

In [136]:
sc_Xt = StandardScaler()
Xt = sc_Xt.fit_transform(Xt)

In [137]:
y_pred10 = ann.predict(Xt)

In [138]:
ypp = y_pred10.argmax(1)

In [139]:
ytt = yt.argmax(1)

In [140]:
cmT = confusion_matrix(ytt, ypp)
accT = accuracy_score(ytt, ypp)

In [141]:
cmT

array([[ 0, 42, 10],
       [ 0, 34, 13],
       [ 0,  0,  0]])

In [142]:
accT

0.3434343434343434