Import Libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset = pd.read_csv("proper.csv", delimiter="\t")

In [3]:
dataset.drop("<VOL>", inplace=True, axis = 1)

In [4]:
dataset.head()

       <DATE>   <OPEN>   <HIGH>    <LOW>  <CLOSE>  <TICKVOL>  <SPREAD>
0  2020.01.01  0.70144  0.70195  0.70051  0.70188       1382         2
1  2020.01.02  0.70188  0.70198  0.69786  0.69832      27492         2
2  2020.01.03  0.69832  0.69865  0.69303  0.69448      32807         2
3  2020.01.05  0.69410  0.69448  0.69326  0.69435       2456         2
4  2020.01.06  0.69434  0.69577  0.69254  0.69369      28884         2

In [5]:
from datetime import datetime
import calendar

In [6]:
dataset['<DATE>'] = dataset['<DATE>'].apply(lambda x: calendar.timegm(datetime.strptime(x, '%Y.%m.%d').utctimetuple()))

In [7]:
dataset['<CLOSE>'].size

6621

In [8]:
def EMA(data, col, n, arr):
    y = n-1
    for i in range(data['<CLOSE>'].size):
        if(i < y):
            arr.append(0)
        elif(i == y):
            av = data.iloc[:i, col].mean()
            arr.append(av)
        else:
            EM = ((data.iloc[i,col] * 2)/(n + 1)) + arr[i-1] * (1-(2/(n+1)))
            arr.append(EM)

In [9]:
EMA12 = []
EMA(dataset, 4, 12, EMA12)
EMA26 = []
EMA(dataset, 4, 26, EMA26)

In [10]:
dataset['<EMA12>'] = EMA12
dataset['<EMA26>'] = EMA26
dataset['<MACD>'] = dataset['<EMA12>'] - dataset['<EMA26>']

In [11]:
dataset.head(20)

,<DATE>,<OPEN>,<HIGH>,<LOW>,<CLOSE>,<TICKVOL>,<SPREAD>,<EMA12>,<EMA26>,<MACD>
0,1577836800,0.70144,0.70195,0.70051,0.70188,1382,2,0.000000,0.0,0.000000
1,1577923200,0.70188,0.70198,0.69786,0.69832,27492,2,0.000000,0.0,0.000000
2,1578009600,0.69832,0.69865,0.69303,0.69448,32807,2,0.000000,0.0,0.000000
3,1578182400,0.69410,0.69448,0.69326,0.69435,2456,2,0.000000,0.0,0.000000
4,1578268800,0.69434,0.69577,0.69254,0.69369,28884,2,0.000000,0.0,0.000000
5,1578355200,0.69370,0.69393,0.68501,0.68597,34415,2,0.000000,0.0,0.000000
6,1578441600,0.68597,0.68856,0.68490,0.68753,45198,2,0.000000,0.0,0.000000
7,1578528000,0.68753,0.68806,0.68503,0.68534,26889,2,0.000000,0.0,0.000000
8,1578614400,0.68534,0.69111,0.68509,0.68987,29148,2,0.000000,0.0,0.000000
9,1578787200,0.68975,0.69057,0.68929,0.68997,1302,2,0.000000,0.0,0.000000
10,1578873600,0.68996,0.69198,0.68947,0.68973,25373,2,0.000000,0.0,0.000000
11,1578960000,0.68973,0.69097,0.68851,0.68946,29334,2,0.691921,0.0,0.691921
12,1579046400,0.68946,0.69166,0.68772,0.69072,28213,2,0.691736,0.0,0.691736
13,1579132800,0.69072,0.69337,0.68878,0.68983,29664,2,0.691443,0.0,0.691443
14,1579219200,0.68983,0.69109,0.68705,0.68713,25708,2,0.690779,0.0,0.690779
15,1579392000,0.68725,0.68830,0.68720,0.68813,1225,2,0.690372,0.0,0.690372
16,1579478400,0.68813,0.68885,0.68553,0.68755,18387,2,0.689938,0.0,0.689938
17,1579564800,0.68755,0.68805,0.68419,0.68470,29455,2,0.689132,0.0,0.689132
18,1579651200,0.68473,0.68563,0.68270,0.68414,26974,2,0.688364,0.0,0.688364
19,1579737600,0.68413,0.68788,0.68294,0.68485,35546,2,0.687823,0.0,0.687823

In [12]:
dataset = dataset.iloc[11:,:]

In [13]:
SIGNAL = []
EMA(dataset, 9, 9, SIGNAL)
dataset['<SIGNAL>'] = SIGNAL

In [14]:
dataset.head(20)

,<DATE>,<OPEN>,<HIGH>,<LOW>,<CLOSE>,<TICKVOL>,<SPREAD>,<EMA12>,<EMA26>,<MACD>,<SIGNAL>
11,1578960000,0.68973,0.69097,0.68851,0.68946,29334,2,0.691921,0.000000,0.691921,0.000000
12,1579046400,0.68946,0.69166,0.68772,0.69072,28213,2,0.691736,0.000000,0.691736,0.000000
13,1579132800,0.69072,0.69337,0.68878,0.68983,29664,2,0.691443,0.000000,0.691443,0.000000
14,1579219200,0.68983,0.69109,0.68705,0.68713,25708,2,0.690779,0.000000,0.690779,0.000000
15,1579392000,0.68725,0.68830,0.68720,0.68813,1225,2,0.690372,0.000000,0.690372,0.000000
16,1579478400,0.68813,0.68885,0.68553,0.68755,18387,2,0.689938,0.000000,0.689938,0.000000
17,1579564800,0.68755,0.68805,0.68419,0.68470,29455,2,0.689132,0.000000,0.689132,0.000000
18,1579651200,0.68473,0.68563,0.68270,0.68414,26974,2,0.688364,0.000000,0.688364,0.000000
19,1579737600,0.68413,0.68788,0.68294,0.68485,35546,2,0.687823,0.000000,0.687823,0.690461
20,1579824000,0.68484,0.68574,0.68176,0.68260,26889,2,0.687020,0.000000,0.687020,0.689772
21,1579996800,0.68117,0.68182,0.68010,0.68013,3866,2,0.685960,0.000000,0.685960,0.689010
22,1580083200,0.68012,0.68170,0.67527,0.67617,29263,2,0.684454,0.000000,0.684454,0.688099
23,1580169600,0.67617,0.67666,0.67370,0.67638,29925,2,0.683212,0.000000,0.683212,0.687121
24,1580256000,0.67638,0.67772,0.67352,0.67532,30617,0,0.681997,0.000000,0.681997,0.686096
25,1580342400,0.67532,0.67533,0.67000,0.67054,37511,2,0.680235,0.687530,-0.007295,0.547418
26,1580428800,0.67054,0.67296,0.66828,0.66860,35169,2,0.678445,0.686127,-0.007683,0.436398
27,1580601600,0.66852,0.66956,0.66841,0.66928,2209,2,0.677035,0.684879,-0.007845,0.347550
28,1580688000,0.66922,0.67070,0.66837,0.66897,34708,2,0.675794,0.683701,-0.007907,0.276458
29,1580774400,0.66896,0.67418,0.66789,0.67311,34536,1,0.675381,0.682916,-0.007535,0.219660
30,1580860800,0.67311,0.67743,0.67237,0.67515,34091,2,0.675346,0.682341,-0.006996,0.174329

In [15]:
dataset = dataset.iloc[9:,:]

In [16]:
dataset.head()

,<DATE>,<OPEN>,<HIGH>,<LOW>,<CLOSE>,<TICKVOL>,<SPREAD>,<EMA12>,<EMA26>,<MACD>,<SIGNAL>
20,1579824000,0.68484,0.68574,0.68176,0.68260,26889,2,0.687020,0.0,0.687020,0.689772
21,1579996800,0.68117,0.68182,0.68010,0.68013,3866,2,0.685960,0.0,0.685960,0.689010
22,1580083200,0.68012,0.68170,0.67527,0.67617,29263,2,0.684454,0.0,0.684454,0.688099
23,1580169600,0.67617,0.67666,0.67370,0.67638,29925,2,0.683212,0.0,0.683212,0.687121
24,1580256000,0.67638,0.67772,0.67352,0.67532,30617,0,0.681997,0.0,0.681997,0.686096

In [17]:
def GL(data, gains, losses, col):
    for i in range(data['<CLOSE>'].size):
        if(i == 0):
            gains.append(0)
            losses.append(0)
        else:
            diff = data.iloc[i, col] - data.iloc[i-1, col]
            if(diff > 0):
                gains.append(diff)
                losses.append(0)
            elif(diff == 0):
                gains.append(0)
                losses.append(0)
            else:
                gains.append(0)
                losses.append(diff)

In [18]:
GAINS = []
LOSSES = []
GL(dataset, GAINS, LOSSES, 4)

In [19]:
dataset['<GAINS>'] = GAINS
dataset['<LOSSES>'] = LOSSES

In [20]:
dataset.head(20)

,<DATE>,<OPEN>,<HIGH>,<LOW>,<CLOSE>,<TICKVOL>,<SPREAD>,<EMA12>,<EMA26>,<MACD>,<SIGNAL>,<GAINS>,<LOSSES>
20,1579824000,0.68484,0.68574,0.68176,0.68260,26889,2,0.687020,0.000000,0.687020,0.689772,0.00000,0.00000
21,1579996800,0.68117,0.68182,0.68010,0.68013,3866,2,0.685960,0.000000,0.685960,0.689010,0.00000,-0.00247
22,1580083200,0.68012,0.68170,0.67527,0.67617,29263,2,0.684454,0.000000,0.684454,0.688099,0.00000,-0.00396
23,1580169600,0.67617,0.67666,0.67370,0.67638,29925,2,0.683212,0.000000,0.683212,0.687121,0.00021,0.00000
24,1580256000,0.67638,0.67772,0.67352,0.67532,30617,0,0.681997,0.000000,0.681997,0.686096,0.00000,-0.00106
25,1580342400,0.67532,0.67533,0.67000,0.67054,37511,2,0.680235,0.687530,-0.007295,0.547418,0.00000,-0.00478
26,1580428800,0.67054,0.67296,0.66828,0.66860,35169,2,0.678445,0.686127,-0.007683,0.436398,0.00000,-0.00194
27,1580601600,0.66852,0.66956,0.66841,0.66928,2209,2,0.677035,0.684879,-0.007845,0.347550,0.00068,0.00000
28,1580688000,0.66922,0.67070,0.66837,0.66897,34708,2,0.675794,0.683701,-0.007907,0.276458,0.00000,-0.00031
29,1580774400,0.66896,0.67418,0.66789,0.67311,34536,1,0.675381,0.682916,-0.007535,0.219660,0.00414,0.00000
30,1580860800,0.67311,0.67743,0.67237,0.67515,34091,2,0.675346,0.682341,-0.006996,0.174329,0.00204,0.00000
31,1580947200,0.67515,0.67649,0.67269,0.67313,27747,2,0.675005,0.681659,-0.006654,0.138132,0.00000,-0.00202
32,1581033600,0.67312,0.67314,0.66622,0.66766,29280,2,0.673875,0.680622,-0.006747,0.109156,0.00000,-0.00547
33,1581206400,0.66670,0.66784,0.66666,0.66699,2433,2,0.672816,0.679612,-0.006797,0.085966,0.00000,-0.00067
34,1581292800,0.66701,0.67074,0.66679,0.66895,30587,2,0.672221,0.678822,-0.006601,0.067452,0.00196,0.00000
35,1581379200,0.66895,0.67366,0.66810,0.67184,27546,2,0.672162,0.678305,-0.006143,0.052733,0.00289,0.00000
36,1581465600,0.67184,0.67499,0.67068,0.67130,29940,2,0.672030,0.677786,-0.005757,0.041035,0.00000,-0.00054
37,1581552000,0.67131,0.67449,0.67096,0.67189,31485,2,0.672008,0.677349,-0.005341,0.031760,0.00059,0.00000
38,1581638400,0.67191,0.67314,0.67092,0.67139,21164,2,0.671913,0.676908,-0.004995,0.024409,0.00000,-0.00050
39,1581811200,0.67208,0.67295,0.67167,0.67254,1271,2,0.672009,0.676584,-0.004575,0.018612,0.00115,0.00000

In [21]:
dataset = dataset.iloc[1:, :]

In [22]:
dataset.head(20)

,<DATE>,<OPEN>,<HIGH>,<LOW>,<CLOSE>,<TICKVOL>,<SPREAD>,<EMA12>,<EMA26>,<MACD>,<SIGNAL>,<GAINS>,<LOSSES>
21,1579996800,0.68117,0.68182,0.68010,0.68013,3866,2,0.685960,0.000000,0.685960,0.689010,0.00000,-0.00247
22,1580083200,0.68012,0.68170,0.67527,0.67617,29263,2,0.684454,0.000000,0.684454,0.688099,0.00000,-0.00396
23,1580169600,0.67617,0.67666,0.67370,0.67638,29925,2,0.683212,0.000000,0.683212,0.687121,0.00021,0.00000
24,1580256000,0.67638,0.67772,0.67352,0.67532,30617,0,0.681997,0.000000,0.681997,0.686096,0.00000,-0.00106
25,1580342400,0.67532,0.67533,0.67000,0.67054,37511,2,0.680235,0.687530,-0.007295,0.547418,0.00000,-0.00478
26,1580428800,0.67054,0.67296,0.66828,0.66860,35169,2,0.678445,0.686127,-0.007683,0.436398,0.00000,-0.00194
27,1580601600,0.66852,0.66956,0.66841,0.66928,2209,2,0.677035,0.684879,-0.007845,0.347550,0.00068,0.00000
28,1580688000,0.66922,0.67070,0.66837,0.66897,34708,2,0.675794,0.683701,-0.007907,0.276458,0.00000,-0.00031
29,1580774400,0.66896,0.67418,0.66789,0.67311,34536,1,0.675381,0.682916,-0.007535,0.219660,0.00414,0.00000
30,1580860800,0.67311,0.67743,0.67237,0.67515,34091,2,0.675346,0.682341,-0.006996,0.174329,0.00204,0.00000
31,1580947200,0.67515,0.67649,0.67269,0.67313,27747,2,0.675005,0.681659,-0.006654,0.138132,0.00000,-0.00202
32,1581033600,0.67312,0.67314,0.66622,0.66766,29280,2,0.673875,0.680622,-0.006747,0.109156,0.00000,-0.00547
33,1581206400,0.66670,0.66784,0.66666,0.66699,2433,2,0.672816,0.679612,-0.006797,0.085966,0.00000,-0.00067
34,1581292800,0.66701,0.67074,0.66679,0.66895,30587,2,0.672221,0.678822,-0.006601,0.067452,0.00196,0.00000
35,1581379200,0.66895,0.67366,0.66810,0.67184,27546,2,0.672162,0.678305,-0.006143,0.052733,0.00289,0.00000
36,1581465600,0.67184,0.67499,0.67068,0.67130,29940,2,0.672030,0.677786,-0.005757,0.041035,0.00000,-0.00054
37,1581552000,0.67131,0.67449,0.67096,0.67189,31485,2,0.672008,0.677349,-0.005341,0.031760,0.00059,0.00000
38,1581638400,0.67191,0.67314,0.67092,0.67139,21164,2,0.671913,0.676908,-0.004995,0.024409,0.00000,-0.00050
39,1581811200,0.67208,0.67295,0.67167,0.67254,1271,2,0.672009,0.676584,-0.004575,0.018612,0.00115,0.00000
40,1581897600,0.67253,0.67333,0.67069,0.67096,16998,2,0.671848,0.676168,-0.004320,0.014026,0.00000,-0.00158

In [23]:
def RS(data, n, rs):
    y = n-1
    for i in range(data['<CLOSE>'].size):
        if(i < y):
            rs.append(0)
        else:
            GA = data.iloc[(i-y):i, 11].mean()
            LO = data.iloc[(i-y):i, 12].mean()
            div = GA/LO
            rs.append(div)

In [24]:
RelStr = []
RS(dataset, 14, RelStr)

In [25]:
dataset['<RS>'] = RelStr

In [26]:
dataset.head(20)

,<DATE>,<OPEN>,<HIGH>,<LOW>,<CLOSE>,<TICKVOL>,<SPREAD>,<EMA12>,<EMA26>,<MACD>,<SIGNAL>,<GAINS>,<LOSSES>,<RS>
21,1579996800,0.68117,0.68182,0.68010,0.68013,3866,2,0.685960,0.000000,0.685960,0.689010,0.00000,-0.00247,0.000000
22,1580083200,0.68012,0.68170,0.67527,0.67617,29263,2,0.684454,0.000000,0.684454,0.688099,0.00000,-0.00396,0.000000
23,1580169600,0.67617,0.67666,0.67370,0.67638,29925,2,0.683212,0.000000,0.683212,0.687121,0.00021,0.00000,0.000000
24,1580256000,0.67638,0.67772,0.67352,0.67532,30617,0,0.681997,0.000000,0.681997,0.686096,0.00000,-0.00106,0.000000
25,1580342400,0.67532,0.67533,0.67000,0.67054,37511,2,0.680235,0.687530,-0.007295,0.547418,0.00000,-0.00478,0.000000
26,1580428800,0.67054,0.67296,0.66828,0.66860,35169,2,0.678445,0.686127,-0.007683,0.436398,0.00000,-0.00194,0.000000
27,1580601600,0.66852,0.66956,0.66841,0.66928,2209,2,0.677035,0.684879,-0.007845,0.347550,0.00068,0.00000,0.000000
28,1580688000,0.66922,0.67070,0.66837,0.66897,34708,2,0.675794,0.683701,-0.007907,0.276458,0.00000,-0.00031,0.000000
29,1580774400,0.66896,0.67418,0.66789,0.67311,34536,1,0.675381,0.682916,-0.007535,0.219660,0.00414,0.00000,0.000000
30,1580860800,0.67311,0.67743,0.67237,0.67515,34091,2,0.675346,0.682341,-0.006996,0.174329,0.00204,0.00000,0.000000
31,1580947200,0.67515,0.67649,0.67269,0.67313,27747,2,0.675005,0.681659,-0.006654,0.138132,0.00000,-0.00202,0.000000
32,1581033600,0.67312,0.67314,0.66622,0.66766,29280,2,0.673875,0.680622,-0.006747,0.109156,0.00000,-0.00547,0.000000
33,1581206400,0.66670,0.66784,0.66666,0.66699,2433,2,0.672816,0.679612,-0.006797,0.085966,0.00000,-0.00067,0.000000
34,1581292800,0.66701,0.67074,0.66679,0.66895,30587,2,0.672221,0.678822,-0.006601,0.067452,0.00196,0.00000,-0.311728
35,1581379200,0.66895,0.67366,0.66810,0.67184,27546,2,0.672162,0.678305,-0.006143,0.052733,0.00289,0.00000,-0.446809
36,1581465600,0.67184,0.67499,0.67068,0.67130,29940,2,0.672030,0.677786,-0.005757,0.041035,0.00000,-0.00054,-0.733538
37,1581552000,0.67131,0.67449,0.67096,0.67189,31485,2,0.672008,0.677349,-0.005341,0.031760,0.00059,0.00000,-0.697439
38,1581638400,0.67191,0.67314,0.67092,0.67139,21164,2,0.671913,0.676908,-0.004995,0.024409,0.00000,-0.00050,-0.781945
39,1581811200,0.67208,0.67295,0.67167,0.67254,1271,2,0.672009,0.676584,-0.004575,0.018612,0.00115,0.00000,-1.074236
40,1581897600,0.67253,0.67333,0.67069,0.67096,16998,2,0.671848,0.676168,-0.004320,0.014026,0.00000,-0.00158,-1.414301

In [27]:
dataset = dataset.iloc[14:, :]

In [28]:
dataset.head(10)

,<DATE>,<OPEN>,<HIGH>,<LOW>,<CLOSE>,<TICKVOL>,<SPREAD>,<EMA12>,<EMA26>,<MACD>,<SIGNAL>,<GAINS>,<LOSSES>,<RS>
35,1581379200,0.66895,0.67366,0.66810,0.67184,27546,2,0.672162,0.678305,-0.006143,0.052733,0.00289,0.00000,-0.446809
36,1581465600,0.67184,0.67499,0.67068,0.67130,29940,2,0.672030,0.677786,-0.005757,0.041035,0.00000,-0.00054,-0.733538
37,1581552000,0.67131,0.67449,0.67096,0.67189,31485,2,0.672008,0.677349,-0.005341,0.031760,0.00059,0.00000,-0.697439
38,1581638400,0.67191,0.67314,0.67092,0.67139,21164,2,0.671913,0.676908,-0.004995,0.024409,0.00000,-0.00050,-0.781945
39,1581811200,0.67208,0.67295,0.67167,0.67254,1271,2,0.672009,0.676584,-0.004575,0.018612,0.00115,0.00000,-1.074236
40,1581897600,0.67253,0.67333,0.67069,0.67096,16998,2,0.671848,0.676168,-0.004320,0.014026,0.00000,-0.00158,-1.414301
41,1581984000,0.67095,0.67096,0.66736,0.66940,26206,2,0.671471,0.675667,-0.004195,0.010382,0.00000,-0.00156,-1.151488
42,1582070400,0.66940,0.67076,0.66653,0.66809,23565,0,0.670951,0.675105,-0.004154,0.007474,0.00000,-0.00131,-1.034846
43,1582156800,0.66806,0.66948,0.66103,0.66117,36387,2,0.669446,0.674073,-0.004627,0.005054,0.00000,-0.00692,-0.632234
44,1582243200,0.66117,0.66389,0.65859,0.66270,31850,2,0.668408,0.673231,-0.004822,0.003079,0.00153,0.00000,-0.320369

In [29]:
dataset["<GROW>"] = dataset["<CLOSE>"] - dataset["<OPEN>"]

In [30]:
dataset.head()

,<DATE>,<OPEN>,<HIGH>,<LOW>,<CLOSE>,<TICKVOL>,<SPREAD>,<EMA12>,<EMA26>,<MACD>,<SIGNAL>,<GAINS>,<LOSSES>,<RS>,<GROW>
35,1581379200,0.66895,0.67366,0.66810,0.67184,27546,2,0.672162,0.678305,-0.006143,0.052733,0.00289,0.00000,-0.446809,0.00289
36,1581465600,0.67184,0.67499,0.67068,0.67130,29940,2,0.672030,0.677786,-0.005757,0.041035,0.00000,-0.00054,-0.733538,-0.00054
37,1581552000,0.67131,0.67449,0.67096,0.67189,31485,2,0.672008,0.677349,-0.005341,0.031760,0.00059,0.00000,-0.697439,0.00058
38,1581638400,0.67191,0.67314,0.67092,0.67139,21164,2,0.671913,0.676908,-0.004995,0.024409,0.00000,-0.00050,-0.781945,-0.00052
39,1581811200,0.67208,0.67295,0.67167,0.67254,1271,2,0.672009,0.676584,-0.004575,0.018612,0.00115,0.00000,-1.074236,0.00046

In [31]:
dataset["<GROW>"] = dataset["<GROW>"].shift(-1)
dataset = dataset.iloc[:-1,:]

In [32]:
dataset.tail()

,<DATE>,<OPEN>,<HIGH>,<LOW>,<CLOSE>,<TICKVOL>,<SPREAD>,<EMA12>,<EMA26>,<MACD>,<SIGNAL>,<GAINS>,<LOSSES>,<RS>,<GROW>
6615,977616000,0.5561,0.5569,0.5555,0.5564,58,50,0.548915,0.542505,0.006410,0.005522,0.0000,-0.0007,-1.899225,-0.0009
6616,977702400,0.5565,0.5583,0.5551,0.5556,337,50,0.549944,0.543475,0.006469,0.005712,0.0000,-0.0008,-1.522059,0.0029
6617,977788800,0.5555,0.5599,0.5552,0.5584,1560,50,0.551245,0.544581,0.006664,0.005902,0.0028,0.0000,-2.070000,-0.0008
6618,977875200,0.5583,0.5597,0.5552,0.5575,3445,50,0.552207,0.545538,0.006670,0.006056,0.0000,-0.0009,-3.671875,-0.0033
6619,977961600,0.5576,0.5579,0.5517,0.5543,3026,50,0.552529,0.546187,0.006342,0.006113,0.0000,-0.0032,-3.082192,0.0044

In [36]:
def CLGrowth(i):
        if(i == 0):
            return 0
        elif(i < 0):
            return 1
        elif(i > 0):
            return 2

In [41]:
dataset['<CLGROWTH>'] = dataset['<GROW>'].apply(CLGrowth)

In [42]:
dataset.head()

,<DATE>,<OPEN>,<HIGH>,<LOW>,<CLOSE>,<TICKVOL>,<SPREAD>,<EMA12>,<EMA26>,<MACD>,<SIGNAL>,<GAINS>,<LOSSES>,<RS>,<GROW>,<CLGROWTH>
35,1581379200,0.66895,0.67366,0.66810,0.67184,27546,2,0.672162,0.678305,-0.006143,0.052733,0.00289,0.00000,-0.446809,-0.00054,1
36,1581465600,0.67184,0.67499,0.67068,0.67130,29940,2,0.672030,0.677786,-0.005757,0.041035,0.00000,-0.00054,-0.733538,0.00058,2
37,1581552000,0.67131,0.67449,0.67096,0.67189,31485,2,0.672008,0.677349,-0.005341,0.031760,0.00059,0.00000,-0.697439,-0.00052,1
38,1581638400,0.67191,0.67314,0.67092,0.67139,21164,2,0.671913,0.676908,-0.004995,0.024409,0.00000,-0.00050,-0.781945,0.00046,2
39,1581811200,0.67208,0.67295,0.67167,0.67254,1271,2,0.672009,0.676584,-0.004575,0.018612,0.00115,0.00000,-1.074236,-0.00157,1

In [43]:
X = dataset.iloc[: ,:-1].values
y = dataset.iloc[:, -1].values

In [47]:
X

array([[ 1.58137920e+09,  6.68950000e-01,  6.73660000e-01, ...,
         0.00000000e+00, -4.46808511e-01, -5.40000000e-04],
       [ 1.58146560e+09,  6.71840000e-01,  6.74990000e-01, ...,
        -5.40000000e-04, -7.33538462e-01,  5.80000000e-04],
       [ 1.58155200e+09,  6.71310000e-01,  6.74490000e-01, ...,
         0.00000000e+00, -6.97438952e-01, -5.20000000e-04],
       ...,
       [ 9.77788800e+08,  5.55500000e-01,  5.59900000e-01, ...,
         0.00000000e+00, -2.07000000e+00, -8.00000000e-04],
       [ 9.77875200e+08,  5.58300000e-01,  5.59700000e-01, ...,
        -9.00000000e-04, -3.67187500e+00, -3.30000000e-03],
       [ 9.77961600e+08,  5.57600000e-01,  5.57900000e-01, ...,
        -3.20000000e-03, -3.08219178e+00,  4.40000000e-03]])

In [49]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X[:, 0:14])
X[:, 0:14] = imputer.transform(X[:, 0:14])

In [50]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state = 1)

In [51]:
from sklearn.preprocessing import StandardScaler

In [52]:
sc_Xtrain = StandardScaler()
X_train = sc_Xtrain.fit_transform(X_train)

sc_Xtest = StandardScaler()
X_test = sc_Xtest.fit_transform(X_test)

<h1>LOGISTIC REGRESION </h1>

In [54]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train, y_train)

/home/hkateu/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression(random_state=0)

In [55]:
y_pred = classifier.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred), 1), y_test.reshape(len(y_test), 1)), 1))

[[1 1]
 [2 2]
 [2 2]
 ...
 [1 1]
 [1 1]
 [1 1]]

In [56]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
acc = accuracy_score(y_test, y_pred)

In [57]:
cm

array([[  0,   0,  15],
       [  0, 610,  25],
       [  0,   1, 666]])

In [58]:
acc

0.9688686408504176

<h1>Testing on new data</h1>

In [59]:
datasetTest = pd.read_csv("toMayData.csv", delimiter="\t")
datasetTest.drop("<VOL>", inplace=True, axis = 1)
datasetTest.head()

       <DATE>   <OPEN>   <HIGH>    <LOW>  <CLOSE>  <TICKVOL>  <SPREAD>
0  2021.01.03  0.76967  0.77140  0.76898  0.77110       2208         2
1  2021.01.04  0.77110  0.77405  0.76424  0.76693      63202         2
2  2021.01.05  0.76693  0.77775  0.76608  0.77624      63957         2
3  2021.01.06  0.77628  0.78201  0.77329  0.78155      89942         2
4  2021.01.07  0.78156  0.78162  0.77255  0.77685      65755         2

In [60]:
datasetTest['<DATE>'] = datasetTest['<DATE>'].apply(lambda x: calendar.timegm(datetime.strptime(x, '%Y.%m.%d').utctimetuple()))

In [61]:
tEMA12 = []
EMA(datasetTest, 4, 12, tEMA12)

In [62]:
datasetTest['<EMA12>'] = tEMA12

In [63]:
datasetTest.head(20)

,<DATE>,<OPEN>,<HIGH>,<LOW>,<CLOSE>,<TICKVOL>,<SPREAD>,<EMA12>
0,1609632000,0.76967,0.77140,0.76898,0.77110,2208,2,0.000000
1,1609718400,0.77110,0.77405,0.76424,0.76693,63202,2,0.000000
2,1609804800,0.76693,0.77775,0.76608,0.77624,63957,2,0.000000
3,1609891200,0.77628,0.78201,0.77329,0.78155,89942,2,0.000000
4,1609977600,0.78156,0.78162,0.77255,0.77685,65755,2,0.000000
5,1610064000,0.77684,0.77987,0.77283,0.77648,77841,2,0.000000
6,1610236800,0.77540,0.77598,0.77117,0.77204,2938,2,0.000000
7,1610323200,0.77204,0.77309,0.76663,0.77071,64368,2,0.000000
8,1610409600,0.77071,0.77774,0.76867,0.77755,59699,2,0.000000
9,1610496000,0.77755,0.77814,0.77217,0.77463,54884,2,0.000000
10,1610582400,0.77463,0.78054,0.77286,0.77755,55408,2,0.000000
11,1610668800,0.77754,0.77886,0.76816,0.77032,56918,2,0.774694
12,1610841600,0.77064,0.77103,0.76830,0.76830,2060,2,0.773710
13,1610928000,0.76831,0.77041,0.76588,0.76847,47028,2,0.772904
14,1611014400,0.76847,0.77251,0.76846,0.77133,50564,1,0.772662
15,1611100800,0.77133,0.77632,0.77004,0.77548,49953,2,0.773095
16,1611187200,0.77548,0.77820,0.77413,0.77595,52107,1,0.773534
17,1611273600,0.77595,0.77688,0.77019,0.77153,49973,2,0.773226
18,1611446400,0.77126,0.77209,0.77054,0.77133,1909,2,0.772934
19,1611532800,0.77138,0.77473,0.76828,0.77147,58122,2,0.772709

In [64]:
datasetTest = datasetTest.iloc[11:,:]

In [65]:
datasetTest.head(20)

,<DATE>,<OPEN>,<HIGH>,<LOW>,<CLOSE>,<TICKVOL>,<SPREAD>,<EMA12>
11,1610668800,0.77754,0.77886,0.76816,0.77032,56918,2,0.774694
12,1610841600,0.77064,0.77103,0.76830,0.76830,2060,2,0.773710
13,1610928000,0.76831,0.77041,0.76588,0.76847,47028,2,0.772904
14,1611014400,0.76847,0.77251,0.76846,0.77133,50564,1,0.772662
15,1611100800,0.77133,0.77632,0.77004,0.77548,49953,2,0.773095
16,1611187200,0.77548,0.77820,0.77413,0.77595,52107,1,0.773534
17,1611273600,0.77595,0.77688,0.77019,0.77153,49973,2,0.773226
18,1611446400,0.77126,0.77209,0.77054,0.77133,1909,2,0.772934
19,1611532800,0.77138,0.77473,0.76828,0.77147,58122,2,0.772709
20,1611619200,0.77146,0.77543,0.76689,0.77533,47662,2,0.773112
21,1611705600,0.77532,0.77637,0.76410,0.76482,74563,2,0.771837
22,1611792000,0.76484,0.76978,0.75919,0.76706,79508,1,0.771102
23,1611878400,0.76707,0.77039,0.76314,0.76413,86634,2,0.770029
24,1612051200,0.76250,0.76303,0.76057,0.76207,3751,2,0.768805
25,1612137600,0.76205,0.76625,0.76124,0.76333,70756,2,0.767962
26,1612224000,0.76333,0.76614,0.75636,0.76056,60054,2,0.766824
27,1612310400,0.76056,0.76370,0.76015,0.76362,50984,2,0.766331
28,1612396800,0.76362,0.76475,0.75881,0.76002,49422,2,0.765360
29,1612483200,0.76002,0.76786,0.75828,0.76773,46669,2,0.765724
30,1612656000,0.76677,0.76815,0.76666,0.76782,2391,2,0.766047

In [66]:
tEMA26 = []
EMA(datasetTest, 4, 26, tEMA26)

In [67]:
datasetTest['<EMA26>'] = tEMA26

In [68]:
datasetTest.head(40)

,<DATE>,<OPEN>,<HIGH>,<LOW>,<CLOSE>,<TICKVOL>,<SPREAD>,<EMA12>,<EMA26>
11,1610668800,0.77754,0.77886,0.76816,0.77032,56918,2,0.774694,0.000000
12,1610841600,0.77064,0.77103,0.76830,0.76830,2060,2,0.773710,0.000000
13,1610928000,0.76831,0.77041,0.76588,0.76847,47028,2,0.772904,0.000000
14,1611014400,0.76847,0.77251,0.76846,0.77133,50564,1,0.772662,0.000000
15,1611100800,0.77133,0.77632,0.77004,0.77548,49953,2,0.773095,0.000000
16,1611187200,0.77548,0.77820,0.77413,0.77595,52107,1,0.773534,0.000000
17,1611273600,0.77595,0.77688,0.77019,0.77153,49973,2,0.773226,0.000000
18,1611446400,0.77126,0.77209,0.77054,0.77133,1909,2,0.772934,0.000000
19,1611532800,0.77138,0.77473,0.76828,0.77147,58122,2,0.772709,0.000000
20,1611619200,0.77146,0.77543,0.76689,0.77533,47662,2,0.773112,0.000000
21,1611705600,0.77532,0.77637,0.76410,0.76482,74563,2,0.771837,0.000000
22,1611792000,0.76484,0.76978,0.75919,0.76706,79508,1,0.771102,0.000000
23,1611878400,0.76707,0.77039,0.76314,0.76413,86634,2,0.770029,0.000000
24,1612051200,0.76250,0.76303,0.76057,0.76207,3751,2,0.768805,0.000000
25,1612137600,0.76205,0.76625,0.76124,0.76333,70756,2,0.767962,0.000000
26,1612224000,0.76333,0.76614,0.75636,0.76056,60054,2,0.766824,0.000000
27,1612310400,0.76056,0.76370,0.76015,0.76362,50984,2,0.766331,0.000000
28,1612396800,0.76362,0.76475,0.75881,0.76002,49422,2,0.765360,0.000000
29,1612483200,0.76002,0.76786,0.75828,0.76773,46669,2,0.765724,0.000000
30,1612656000,0.76677,0.76815,0.76666,0.76782,2391,2,0.766047,0.000000
31,1612742400,0.76782,0.77148,0.76511,0.77082,36759,2,0.766781,0.000000
32,1612828800,0.77081,0.77428,0.77039,0.77397,41605,2,0.767887,0.000000
33,1612915200,0.77397,0.77559,0.77172,0.77236,50490,2,0.768575,0.000000
34,1613001600,0.77235,0.77715,0.77126,0.77516,38125,2,0.769588,0.000000
35,1613088000,0.77516,0.77644,0.77180,0.77610,32538,2,0.770590,0.000000
36,1613260800,0.77616,0.77674,0.77581,0.77628,1607,2,0.771465,0.769163
37,1613347200,0.77629,0.77887,0.77595,0.77852,26591,2,0.772551,0.769856
38,1613433600,0.77852,0.78052,0.77305,0.77353,49441,2,0.772701,0.770128
39,1613520000,0.77353,0.77718,0.77243,0.77581,53090,2,0.773180,0.770549
40,1613606400,0.77578,0.77895,0.77311,0.77682,54137,2,0.773740,0.771014
41,1613692800,0.77682,0.78772,0.77575,0.78684,55228,2,0.775755,0.772186
42,1613865600,0.78705,0.78918,0.78659,0.78822,2069,2,0.777673,0.773374
43,1613952000,0.78822,0.79291,0.78552,0.79141,57335,2,0.779786,0.774710
44,1614038400,0.79141,0.79345,0.78803,0.79069,61275,2,0.781464,0.775894
45,1614124800,0.79069,0.79777,0.78951,0.79756,66777,1,0.783940,0.777498
46,1614211200,0.79755,0.80071,0.78585,0.78623,84984,2,0.784292,0.778145
47,1614297600,0.78623,0.78717,0.76920,0.77030,91560,2,0.782140,0.777564
48,1614470400,0.77102,0.77590,0.77073,0.77524,2837,2,0.781078,0.777392
49,1614556800,0.77526,0.77868,0.77216,0.77732,64047,2,0.780500,0.777387
50,1614643200,0.77730,0.78375,0.77357,0.78241,72203,2,0.780794,0.777759

In [69]:
datasetTest = datasetTest.iloc[25:,:]

In [70]:
datasetTest.head(20)

,<DATE>,<OPEN>,<HIGH>,<LOW>,<CLOSE>,<TICKVOL>,<SPREAD>,<EMA12>,<EMA26>
36,1613260800,0.77616,0.77674,0.77581,0.77628,1607,2,0.771465,0.769163
37,1613347200,0.77629,0.77887,0.77595,0.77852,26591,2,0.772551,0.769856
38,1613433600,0.77852,0.78052,0.77305,0.77353,49441,2,0.772701,0.770128
39,1613520000,0.77353,0.77718,0.77243,0.77581,53090,2,0.773180,0.770549
40,1613606400,0.77578,0.77895,0.77311,0.77682,54137,2,0.773740,0.771014
41,1613692800,0.77682,0.78772,0.77575,0.78684,55228,2,0.775755,0.772186
42,1613865600,0.78705,0.78918,0.78659,0.78822,2069,2,0.777673,0.773374
43,1613952000,0.78822,0.79291,0.78552,0.79141,57335,2,0.779786,0.774710
44,1614038400,0.79141,0.79345,0.78803,0.79069,61275,2,0.781464,0.775894
45,1614124800,0.79069,0.79777,0.78951,0.79756,66777,1,0.783940,0.777498
46,1614211200,0.79755,0.80071,0.78585,0.78623,84984,2,0.784292,0.778145
47,1614297600,0.78623,0.78717,0.76920,0.77030,91560,2,0.782140,0.777564
48,1614470400,0.77102,0.77590,0.77073,0.77524,2837,2,0.781078,0.777392
49,1614556800,0.77526,0.77868,0.77216,0.77732,64047,2,0.780500,0.777387
50,1614643200,0.77730,0.78375,0.77357,0.78241,72203,2,0.780794,0.777759
51,1614729600,0.78242,0.78381,0.77523,0.77527,68438,2,0.779944,0.777574
52,1614816000,0.77527,0.78150,0.77043,0.77141,87996,2,0.778631,0.777118
53,1614902400,0.77141,0.77266,0.76217,0.76820,84475,2,0.777026,0.776457
54,1615075200,0.76915,0.77224,0.76909,0.77080,2939,2,0.776068,0.776038
55,1615161600,0.77080,0.77140,0.76350,0.76553,79461,2,0.774447,0.775260

In [71]:
datasetTest['<MACD>'] = datasetTest['<EMA12>'] - datasetTest['<EMA26>']

In [72]:
tSIGNAL = []
EMA(datasetTest, 9, 9, tSIGNAL)
datasetTest['<SIGNAL>'] = tSIGNAL

In [73]:
datasetTest.head(20)

,<DATE>,<OPEN>,<HIGH>,<LOW>,<CLOSE>,<TICKVOL>,<SPREAD>,<EMA12>,<EMA26>,<MACD>,<SIGNAL>
36,1613260800,0.77616,0.77674,0.77581,0.77628,1607,2,0.771465,0.769163,0.002302,0.000000
37,1613347200,0.77629,0.77887,0.77595,0.77852,26591,2,0.772551,0.769856,0.002695,0.000000
38,1613433600,0.77852,0.78052,0.77305,0.77353,49441,2,0.772701,0.770128,0.002573,0.000000
39,1613520000,0.77353,0.77718,0.77243,0.77581,53090,2,0.773180,0.770549,0.002630,0.000000
40,1613606400,0.77578,0.77895,0.77311,0.77682,54137,2,0.773740,0.771014,0.002726,0.000000
41,1613692800,0.77682,0.78772,0.77575,0.78684,55228,2,0.775755,0.772186,0.003569,0.000000
42,1613865600,0.78705,0.78918,0.78659,0.78822,2069,2,0.777673,0.773374,0.004299,0.000000
43,1613952000,0.78822,0.79291,0.78552,0.79141,57335,2,0.779786,0.774710,0.005076,0.000000
44,1614038400,0.79141,0.79345,0.78803,0.79069,61275,2,0.781464,0.775894,0.005570,0.003234
45,1614124800,0.79069,0.79777,0.78951,0.79756,66777,1,0.783940,0.777498,0.006442,0.003875
46,1614211200,0.79755,0.80071,0.78585,0.78623,84984,2,0.784292,0.778145,0.006147,0.004330
47,1614297600,0.78623,0.78717,0.76920,0.77030,91560,2,0.782140,0.777564,0.004576,0.004379
48,1614470400,0.77102,0.77590,0.77073,0.77524,2837,2,0.781078,0.777392,0.003686,0.004240
49,1614556800,0.77526,0.77868,0.77216,0.77732,64047,2,0.780500,0.777387,0.003113,0.004015
50,1614643200,0.77730,0.78375,0.77357,0.78241,72203,2,0.780794,0.777759,0.003035,0.003819
51,1614729600,0.78242,0.78381,0.77523,0.77527,68438,2,0.779944,0.777574,0.002370,0.003529
52,1614816000,0.77527,0.78150,0.77043,0.77141,87996,2,0.778631,0.777118,0.001513,0.003126
53,1614902400,0.77141,0.77266,0.76217,0.76820,84475,2,0.777026,0.776457,0.000569,0.002615
54,1615075200,0.76915,0.77224,0.76909,0.77080,2939,2,0.776068,0.776038,0.000030,0.002098
55,1615161600,0.77080,0.77140,0.76350,0.76553,79461,2,0.774447,0.775260,-0.000813,0.001516

In [74]:
datasetTest = datasetTest.iloc[8:,:]

In [75]:
tGAINS = []
tLOSSES = []
GL(datasetTest, tGAINS, tLOSSES, 4)

In [76]:
datasetTest['<GAINS>'] = tGAINS
datasetTest['<LOSSES>'] = tLOSSES

In [77]:
tRelStr = []
RS(datasetTest, 14, tRelStr)

In [78]:
datasetTest['<RS>'] = tRelStr

In [79]:
datasetTest["<GROW>"] = datasetTest["<CLOSE>"] - datasetTest["<OPEN>"]

In [80]:
datasetTest.head(40)

,<DATE>,<OPEN>,<HIGH>,<LOW>,<CLOSE>,<TICKVOL>,<SPREAD>,<EMA12>,<EMA26>,<MACD>,<SIGNAL>,<GAINS>,<LOSSES>,<RS>,<GROW>
44,1614038400,0.79141,0.79345,0.78803,0.79069,61275,2,0.781464,0.775894,0.005570,0.003234,0.00000,0.00000,0.000000,-0.00072
45,1614124800,0.79069,0.79777,0.78951,0.79756,66777,1,0.783940,0.777498,0.006442,0.003875,0.00687,0.00000,0.000000,0.00687
46,1614211200,0.79755,0.80071,0.78585,0.78623,84984,2,0.784292,0.778145,0.006147,0.004330,0.00000,-0.01133,0.000000,-0.01132
47,1614297600,0.78623,0.78717,0.76920,0.77030,91560,2,0.782140,0.777564,0.004576,0.004379,0.00000,-0.01593,0.000000,-0.01593
48,1614470400,0.77102,0.77590,0.77073,0.77524,2837,2,0.781078,0.777392,0.003686,0.004240,0.00494,0.00000,0.000000,0.00422
49,1614556800,0.77526,0.77868,0.77216,0.77732,64047,2,0.780500,0.777387,0.003113,0.004015,0.00208,0.00000,0.000000,0.00206
50,1614643200,0.77730,0.78375,0.77357,0.78241,72203,2,0.780794,0.777759,0.003035,0.003819,0.00509,0.00000,0.000000,0.00511
51,1614729600,0.78242,0.78381,0.77523,0.77527,68438,2,0.779944,0.777574,0.002370,0.003529,0.00000,-0.00714,0.000000,-0.00715
52,1614816000,0.77527,0.78150,0.77043,0.77141,87996,2,0.778631,0.777118,0.001513,0.003126,0.00000,-0.00386,0.000000,-0.00386
53,1614902400,0.77141,0.77266,0.76217,0.76820,84475,2,0.777026,0.776457,0.000569,0.002615,0.00000,-0.00321,0.000000,-0.00321
54,1615075200,0.76915,0.77224,0.76909,0.77080,2939,2,0.776068,0.776038,0.000030,0.002098,0.00260,0.00000,0.000000,0.00165
55,1615161600,0.77080,0.77140,0.76350,0.76553,79461,2,0.774447,0.775260,-0.000813,0.001516,0.00000,-0.00527,0.000000,-0.00527
56,1615248000,0.76553,0.77258,0.76213,0.77150,66150,2,0.773994,0.774981,-0.000988,0.001015,0.00597,0.00000,0.000000,0.00597
57,1615334400,0.77150,0.77455,0.76685,0.77301,62543,2,0.773842,0.774835,-0.000993,0.000613,0.00151,0.00000,-0.589431,0.00151
58,1615420800,0.77301,0.77936,0.77230,0.77853,55882,2,0.774564,0.775109,-0.000545,0.000382,0.00552,0.00000,-0.621737,0.00552
59,1615507200,0.77850,0.78006,0.77241,0.77584,62817,2,0.774760,0.775163,-0.000403,0.000225,0.00000,-0.00269,-0.592854,-0.00266
60,1615680000,0.77500,0.77632,0.77457,0.77620,2460,2,0.774981,0.775240,-0.000258,0.000128,0.00036,0.00000,-0.727297,0.00120
61,1615766400,0.77621,0.77755,0.77056,0.77479,52439,2,0.774952,0.775207,-0.000255,0.000052,0.00000,-0.00141,-1.266125,-0.00142
62,1615852800,0.77479,0.77574,0.77106,0.77460,45620,2,0.774898,0.775162,-0.000264,-0.000011,0.00000,-0.00019,-0.980916,-0.00019
63,1615939200,0.77461,0.78143,0.76991,0.78142,52045,2,0.775901,0.775625,0.000276,0.000046,0.00682,0.00000,-0.885570,0.00681
64,1616025600,0.78145,0.78491,0.77492,0.77524,69001,2,0.775800,0.775597,0.000203,0.000077,0.00000,-0.00618,-0.958351,-0.00621
65,1616112000,0.77528,0.77722,0.77174,0.77459,59565,2,0.775613,0.775522,0.000091,0.000080,0.00000,-0.00065,-0.998685,-0.00069
66,1616284800,0.77085,0.77298,0.77078,0.77225,2574,2,0.775096,0.775280,-0.000184,0.000027,0.00000,-0.00234,-1.162245,0.00140
67,1616371200,0.77226,0.77563,0.77049,0.77445,47108,2,0.774997,0.775218,-0.000222,-0.000022,0.00220,0.00000,-1.216231,0.00219
68,1616457600,0.77443,0.77466,0.75990,0.76063,57340,2,0.772786,0.774138,-0.001351,-0.000288,0.00000,-0.01382,-1.194875,-0.01380
69,1616544000,0.76065,0.76280,0.75776,0.75906,52875,2,0.770675,0.773021,-0.002346,-0.000700,0.00000,-0.00157,-0.820381,-0.00159
70,1616630400,0.75909,0.76140,0.75630,0.75923,58277,2,0.768914,0.771999,-0.003085,-0.001177,0.00017,0.00000,-0.568804,0.00014
71,1616716800,0.75923,0.76409,0.75875,0.76408,43799,2,0.768170,0.771413,-0.003242,-0.001590,0.00485,0.00000,-0.522357,0.00485
72,1616889600,0.76333,0.76448,0.76244,0.76369,2113,2,0.767481,0.770841,-0.003360,-0.001944,0.00000,-0.00039,-0.499133,0.00036
73,1616976000,0.76370,0.76556,0.76150,0.76384,46980,2,0.766921,0.770322,-0.003401,-0.002235,0.00015,0.00000,-0.542373,0.00014
74,1617062400,0.76385,0.76640,0.75848,0.76085,46117,2,0.765987,0.769620,-0.003634,-0.002515,0.00000,-0.00299,-0.534463,-0.00300
75,1617148800,0.76085,0.76365,0.75881,0.75938,43665,4,0.764970,0.768862,-0.003891,-0.002790,0.00000,-0.00147,-0.504444,-0.00147
76,1617235200,0.75938,0.76197,0.75319,0.76165,46254,4,0.764460,0.768328,-0.003868,-0.003006,0.00227,0.00000,-0.482489,0.00227
77,1617321600,0.76168,0.76374,0.75908,0.76094,11234,4,0.763918,0.767780,-0.003862,-0.003177,0.00000,-0.00071,-0.327780,-0.00074
78,1617494400,0.76042,0.76208,0.76016,0.76192,2194,4,0.763611,0.767346,-0.003736,-0.003289,0.00098,0.00000,-0.402673,0.00150
79,1617580800,0.76193,0.76604,0.75982,0.76572,30929,2,0.763935,0.767226,-0.003291,-0.003289,0.00380,0.00000,-0.455990,0.00379
80,1617667200,0.76570,0.76681,0.76058,0.76661,44297,2,0.764347,0.767180,-0.002834,-0.003198,0.00089,0.00000,-0.688305,0.00091
81,1617753600,0.76661,0.76771,0.76005,0.76133,46381,2,0.763883,0.766747,-0.002864,-0.003131,0.00000,-0.00528,-0.625776,-0.00528
82,1617840000,0.76133,0.76602,0.76025,0.76563,38729,4,0.764151,0.766664,-0.002513,-0.003008,0.00430,0.00000,-1.056406,0.00430
83,1617926400,0.76565,0.76608,0.75881,0.76185,37783,4,0.763797,0.766308,-0.002510,-0.002908,0.00000,-0.00378,-1.606089,-0.00380

In [81]:
datasetTest["<GROW>"] = datasetTest["<GROW>"].shift(-1)
datasetTest = datasetTest.iloc[:-1,:]

In [82]:
datasetTest.tail(20)

,<DATE>,<OPEN>,<HIGH>,<LOW>,<CLOSE>,<TICKVOL>,<SPREAD>,<EMA12>,<EMA26>,<MACD>,<SIGNAL>,<GAINS>,<LOSSES>,<RS>,<GROW>
93,1618963200,0.77224,0.77622,0.76993,0.77539,43191,0,0.770709,0.769069,0.001640,0.000132,0.00318,0.00000,-1.380645,-0.00503
94,1619049600,0.77541,0.77645,0.76904,0.77038,49217,2,0.770659,0.769166,0.001493,0.000404,0.00000,-0.00501,-1.514956,0.00446
95,1619136000,0.77040,0.77603,0.77001,0.77486,35725,2,0.771305,0.769588,0.001717,0.000667,0.00448,0.00000,-1.539333,0.00012
96,1619308800,0.77410,0.77527,0.77386,0.77422,1548,2,0.771753,0.769931,0.001823,0.000898,0.00000,-0.00064,-1.550060,0.00539
97,1619395200,0.77427,0.78150,0.77416,0.77966,34050,2,0.772970,0.770651,0.002318,0.001182,0.00544,0.00000,-1.906891,-0.00290
98,1619481600,0.77963,0.78035,0.77614,0.77673,31934,2,0.773548,0.771102,0.002447,0.001435,0.00000,-0.00293,-2.285924,0.00337
99,1619568000,0.77672,0.78061,0.77249,0.78009,38198,2,0.774555,0.771767,0.002787,0.001705,0.00336,0.00000,-1.847314,-0.00240
100,1619654400,0.78009,0.78177,0.77501,0.77769,37810,2,0.775037,0.772206,0.002831,0.001931,0.00000,-0.00240,-1.928787,-0.00652
101,1619740800,0.77769,0.77840,0.76960,0.77117,36460,2,0.774442,0.772129,0.002313,0.002007,0.00000,-0.00652,-1.276226,0.00080
102,1619913600,0.77120,0.77213,0.77118,0.77200,1107,1,0.774066,0.772120,0.001947,0.001995,0.00083,0.00000,-0.846607,0.00380
103,1620000000,0.77201,0.77666,0.77061,0.77581,29734,2,0.774335,0.772393,0.001941,0.001984,0.00381,0.00000,-0.942389,-0.00450
104,1620086400,0.77580,0.77608,0.76750,0.77130,44880,2,0.773868,0.772312,0.001556,0.001898,0.00000,-0.00451,-1.206072,0.00378
105,1620172800,0.77132,0.77547,0.77040,0.77510,33905,1,0.774057,0.772519,0.001539,0.001827,0.00380,0.00000,-0.803810,0.00360
106,1620259200,0.77509,0.77881,0.77010,0.77869,40779,2,0.774770,0.772976,0.001794,0.001820,0.00359,0.00000,-1.131304,0.00566
107,1620345600,0.77869,0.78621,0.77608,0.78435,38839,2,0.776244,0.773818,0.002426,0.001941,0.00566,0.00000,-1.149932,0.00106
108,1620518400,0.78475,0.78620,0.78427,0.78581,1498,2,0.777716,0.774707,0.003009,0.002155,0.00146,0.00000,-1.821765,-0.00179
109,1620604800,0.78581,0.78907,0.78267,0.78402,40565,2,0.778686,0.775397,0.003289,0.002382,0.00000,-0.00179,-1.644118,-0.00031
110,1620691200,0.78405,0.78563,0.78200,0.78374,44807,2,0.779463,0.776015,0.003449,0.002595,0.00000,-0.00028,-1.539945,-0.01054
111,1620777600,0.78375,0.78421,0.77191,0.77321,52084,2,0.778501,0.775807,0.002694,0.002615,0.00000,-0.01053,-1.221378,-0.00085
112,1620864000,0.77321,0.77459,0.76880,0.77236,51149,2,0.777556,0.775551,0.002005,0.002493,0.00000,-0.00085,-0.864771,0.00585

In [83]:
datasetTest['<CLGROWTH>'] = datasetTest['<GROW>'].apply(CLGrowth)

In [84]:
datasetTest.head()

,<DATE>,<OPEN>,<HIGH>,<LOW>,<CLOSE>,<TICKVOL>,<SPREAD>,<EMA12>,<EMA26>,<MACD>,<SIGNAL>,<GAINS>,<LOSSES>,<RS>,<GROW>,<CLGROWTH>
44,1614038400,0.79141,0.79345,0.78803,0.79069,61275,2,0.781464,0.775894,0.005570,0.003234,0.00000,0.00000,0.0,0.00687,2
45,1614124800,0.79069,0.79777,0.78951,0.79756,66777,1,0.783940,0.777498,0.006442,0.003875,0.00687,0.00000,0.0,-0.01132,1
46,1614211200,0.79755,0.80071,0.78585,0.78623,84984,2,0.784292,0.778145,0.006147,0.004330,0.00000,-0.01133,0.0,-0.01593,1
47,1614297600,0.78623,0.78717,0.76920,0.77030,91560,2,0.782140,0.777564,0.004576,0.004379,0.00000,-0.01593,0.0,0.00422,2
48,1614470400,0.77102,0.77590,0.77073,0.77524,2837,2,0.781078,0.777392,0.003686,0.004240,0.00494,0.00000,0.0,0.00206,2

In [85]:
Xt = datasetTest.iloc[: ,:-1].values
yt = datasetTest.iloc[:, -1].values

In [86]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(Xt[:, 0:14])
Xt[:, 0:14] = imputer.transform(Xt[:, 0:14])

In [87]:
sc_Xt = StandardScaler()
Xt = sc_Xt.fit_transform(Xt)

In [88]:
y_pred10 = classifier.predict(Xt)

In [90]:
np.set_printoptions(precision=2)
print(np.concatenate((y_pred10.reshape(len(y_pred10), 1), yt.reshape(len(yt), 1)), 1))

[[2 2]
 [1 1]
 [1 1]
 [2 2]
 [2 2]
 [2 2]
 [1 1]
 [1 1]
 [1 1]
 [2 2]
 [1 1]
 [2 2]
 [2 2]
 [2 2]
 [1 1]
 [2 2]
 [1 1]
 [2 1]
 [2 2]
 [1 1]
 [1 1]
 [2 2]
 [2 2]
 [1 1]
 [1 1]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [1 1]
 [1 1]
 [2 2]
 [1 1]
 [2 2]
 [2 2]
 [2 2]
 [1 1]
 [2 2]
 [1 1]
 [2 2]
 [0 2]
 [2 2]
 [2 2]
 [2 2]
 [1 1]
 [1 1]
 [2 2]
 [1 1]
 [2 2]
 [1 1]
 [2 2]
 [2 2]
 [2 2]
 [1 1]
 [2 2]
 [1 1]
 [1 1]
 [2 2]
 [2 2]
 [1 1]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [2 2]]

In [94]:
from sklearn.metrics import confusion_matrix, accuracy_score
cmT = confusion_matrix(yt, y_pred10)
accT = accuracy_score(yt, y_pred10)

In [95]:
cmT

array([[ 0,  0,  0],
       [ 0, 29,  1],
       [ 1,  0, 38]])

In [97]:
accT

0.9710144927536232